### PR TITLE
Add other captcha providers / update templates

### PR DESCRIPTION
**Pull request by LaurenceJJones**

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Also to spark a conversation whilst we are here, most captcha providers support a call back function so we can remove the useless submit and automatically pass if the user succeeds can help reduce one click.

image

**Comment by ciphermenial** [comment]
Can this be added to the HAProxy bouncer too?

**Comment by LaurenceJJones** [comment]
> Can this be added to the HAProxy bouncer too?

Yes, we should really just integrate the plugins at build time instead of copy pasting them. 🤔

**Comment by he2ss** [comment]
Just need a proper documentation on how we can switch between providers. Otherwise lgtm :+1:

**Pull request merged**
