### PR TITLE
Fix http error reporting

### PR DESCRIPTION
**Pull request by mmetc**
The connection error was shadowed by the variable inside the if block.

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Fix for #41

**Review by LaurenceJJones — APPROVED** [review]
LGTM but I changed it to my version. Request @mmetc to review

**Comment by mmetc** [comment]
lgtm but in general I'd rather avoid the double negatives: refresh=true|false is more readable than setRefreshFalse=false|true, at the cost of making it mandatory, and the nil checks would not be needed anymore

**Comment by LaurenceJJones** [comment]
> lgtm but in general I'd rather avoid the double negatives

Yeah I agree, it was more a hacky way to get round passing another var to function

**Pull request closed without merging**
